MATCHMAKING_MISMATCH_TITLE코1=Wrong multiplayer system
MATCHMAKING_MISMATCH_DESC코1=The other user is using another multiplayer system, please restart the game and select $NAME$
MATCHMAKING_MISMATCH_DESC_EGS코0=The other user is hosting using the Steam backend, which is unsupported on the Epic build of the game
