INVITE_ACCEPTED_INGAME_TITLE코0=멀티플레이어 세션에 참여할 수 없습니다.
INVITE_ACCEPTED_INGAME_DESC코0=메인 메뉴 또는 매치메이킹 메뉴에서만 멀티플레이어 세션에 참여할 수 있습니다. 게임을 다시 시작하고 다시 참여하십시오.
NAME_INVALID_TITLE코0=이름이 잘못되었습니다
NAME_INVALID_DESC코0=이름이 잘못되었습니다. 이름은 비어 있으면 안 되며 특수 문자가 없어야 합니다. 다른 이름을 선택하십시오.
HAVE_LESS_FREE_EXPLORERS_THAN코0=보다 적은 수의 무료 탐험가 보유
HAVE_MORE_FREE_EXPLORERS_THAN코0=최소한 보유하고 있는 무료 탐험가의 수
epic_button_login코0=당신은 현재 로그인 되어있지 않습니다. 에픽 계정에 로그인하려면 여기를 클릭하십시오.
epic_button_login_inprogress코0=로그인 프로세스가 진행 중입니다. 에픽 계정에 로그인하려면 여기를 클릭하십시오.
epic_button_logout코0=현재 $ACCOUNT$ 계정으로 로그인하고 있습니다. 여기를 우클릭하여 에픽 계정에서 로그아웃하십시오. 에픽 친구 목록을 보려면 클릭하십시오.
epic_button_logout_no_overlay코0=당신은 현재 $ACCOUNT$ 계정에 로그인되어 있습니다. 에픽 계정에서 로그아웃하려면 여기를 클릭하세요.
epic_button_disabled코0=에픽 서비스를 초기화하는데 실패했습니다, 에픽 게임즈 런처를 설치했는지 확인하십시오.
CLOUDSAVE_ERROR_TITLE코0=클라우드 저장 오류
CLOUDSAVE_SYNCING코0=동기화
CLOUDSAVE_ERROR코0=오류
CLOUDSAVE_FILENAMEINVALID코0=파일 이름이 잘못되었습니다.
CLOUDSAVE_FILENAMELENGTHINVALID코0=파일 이름이 너무 깁니다.
CLOUDSAVE_FILESIZETOOLARGE코0=파일이 너무 큽니다.
CLOUDSAVE_USERTHROTTLED코0=제한을 초과하므로 작업을 수행할 수 없습니다.
CLOUDSAVE_FILECORRUPTED코0=파일이 손상되었습니다. 게임을 다시 시작하거나 다시 저장하십시오.
EGS_DISCONNECTED_TITLE코0=연결 끊어짐
EGS_DISCONNECTED_DESC코1=에픽 서비스에서 연결이 끊어졌습니다. 클라우드 저장 또는 업적과 같은 일부 기능이 작동하지 않을 수 있습니다. 다시 연결하시겠습니까?
EGS_RECONNECT_FAILED_TITLE코1=에픽에 로그인 실패
EGS_RECONNECT_FAILED_DESC코1=에픽 서비스 연결에 실패했습니다. 클라우드 저장 또는 업적과 같은 일부 기능이 작동하지 않을 수 있습니다. 다시 시도하시겠습니까?
