a_new_destiny_awaits코0=새 운명이 기다린다
into_the_wild코0=야생 속으로
strategy_reborn코0=전략 재탄생
encounters_in_the_sun_ea코0=태양 속에서의 조우
neverending_dunes코0=끝없는 모래언덕
the_long_walk_ea코0=머나먼 여정
take_native_american_land_desc코0=
