###ETH FLAVOR EVENTS###
flavor_eth.29.t코0=[Root.GetName]의 이동하는 수도
flavor_eth.29.desc코1=[Root.GetName]의 느구서 너거스트(황제)들은 그들이 필요하다고 보는 지역들로 궁정을 옮겨다녔기 때문에 [Root.GetName]의 수도는 결코 고정되지 않았습니다. 이 제도는 새로운 수도의 주변 지방이 솔로몬 왕조의 손아귀 아래에 있도록 보장했지만, 나머지 [Root.GetName]의 지역들은 대부분이 자치적이었으며, 그 결과 이 지역들에 대한 통제권을 상실했습니다.
flavor_eth.29.a코0=알겠다.
flavor_eth.30.t코0=영구적인 수도 확립
flavor_eth.30.desc코0=[Root.Monarch.GetTitle] [Root.Monarch.GetName](은)는 [Root.GetName] 국가를 근대화시켰으며, [GetYear]년 [Root.Capital.GetName]에 첫 번째 수도를 설립했습니다. 또한, [Root.Monarch.GetSheHe]는 중요한 결정들을 오래 끌어온 종교적 논쟁들을 해결했고, 정부를 중앙집권화 했습니다. [Root.Monarch.GetHerHisCap] 업적들은 [Root.GetAdjective]의 역사에서 영원히 기억될 것입니다.
flavor_eth.30.a코0=마침내. 더 이상 이동하는 수도는 없다.
flavor_eth.30.b코0=나는 이동하는 수도가 좋다.
###MAL FLAVOR EVENTS###
###SON FLAVOR EVENTS###
###COMET EVENTS###
###KONGO FLAVOR EVENTS###
###MUTAPA FLAVOR EVENTS###
###AJUURAN FLAVOR EVENTS###
###ADA FLAVOR EVENTS###
###HEIR CULT###
###COUNTRIES###
###CULTURES###
###MERCENARY COMPANIES###
###UNIT MODIFIER###
###GOVERNMENT REFORMS###
negusa_nagast코0=느구서 너거스트 군주정
negusa_nagast_legacy코0=느구서 너거스트 군주정
negusa_nagast_legacy_desc코0=에티오피아는 제국이지만, 느구서 너거스트(황제)의 권위를 집행할 수 있는 적절한 수단들이 부족합니다. 느구서 너거스트 군주정은 에티오피아가 될 제국의 초기 형태의 국가이며, 이 정부 개혁은 장점보다는 더 많은 문제들을 일으키는 종교적 분열, 중앙 권력의 부족 그리고 이동하는 수도가 특징입니다.
negusa_nagast_desc코0=에티오피아는 제국이지만, 느구서 너거스트(황제)의 권위를 집행할 수 있는 적절한 수단들이 부족합니다. 느구서 너거스트 군주정은 에티오피아가 될 제국의 초기 형태의 국가이며, 이 정부 개혁은 장점보다는 더 많은 문제들을 일으키는 종교적 분열, 중앙 권력의 부족 그리고 이동하는 수도가 특징입니다.
solomonic_empire코0=솔로몬 제국
solomonic_empire_legacy코0=솔로몬 제국
solomonic_empire_legacy_desc코0=솔로몬 제국은 국가가 통합된 후의 에티오피아의 정부 개혁입니다. 종교적 논쟁은 더 이상 관심사가 아니며 제국은 이제 외부로 지배력을 행사하고 있습니다.
solomonic_empire_desc코1=솔로몬 제국은 국가가 통합된 후의 에티오피아의 정부 개혁입니다. 종교적 논쟁은 더 이상 관심사가 아니며 제국은 이제 외부로 지배력을 행사하고 있습니다.
###ESTATE PRIVILEGES###
estate_church_yakobs_churches_desc코1=느구서 너거스트 자라 야콥은 한 때 분열되었던 콥트 교회를 주말에 대한 다른 견해들에 대한 타협안을 찾아서 단결시켰습니다. 그의 행동 덕분에, 성직자 계급은 다른 독실한 신자들에게 야콥의 가르침을 보다 쉽게 가르칠 수 있는 개혁을 도입했습니다.
###TRADE MODIFIER###
###SCRIPTED EFFECTS AND TRIGGERS###
###DISASTER###
###BUILDINGS###
###IDEAS###
###DECISIONS###
###MAL DECISIONS###
###CUSTOM LOCALIZATION###
###JEWISH MECHANICS###
###OPINION###
###DECISIONS###
ethiopia_nation_title코0=솔로몬 왕조의 유산 복원
ethiopia_nation_desc코1=에티오피아 제국은 악숨 제국의 정신적인 계승자이며, 전설적인 솔로몬 왕과 시바 여왕의 자손들의 집이자, 콥트교 신앙의 수호자입니다. 에티오피아의 멸망은 에티오피아 콥트교 신앙의 비극이었지만, 에티오피아의 정신은 계속 살아남아 있으며, 우리와 같은 자격있는 후계자에 의해 부활되기를 기다리고 있습니다!
###ZIM MODIFIERS###
###ADAL MODIFIERS###
###CATHOLICISM###
###PP###
###MISSIONS###
eth_reform_the_negusa_government_ct코0=§Y솔로몬 제국§! 정부 개혁을 해제합니다.
###MAL MISSIONS###
###SON MISSIONS###
###KON MISSIONS###
###ZIM MISSIONS###
###AJU MISSIONS###
###ZAN MISSIONS###
###AJU MODIFIERS###
###ZAN MISSIONS###
###ETHIOPIA MISSION REWARDS###
desc_eth_negusa_nagast_issues코0=에티오피아에는 중앙집권화가 거의 없습니다. 통제해야 할 지역으로 수도를 옮겨다니는, 느구서 너거스트의 존재만이 권위를 발휘할 수 있는 유일한 가능성입니다.
###OPINION MODIFIERS###
###MALI MISSION MODIFIERS###
###MALI EVENT MODIFIERS###
###ESTATES###
###ESTATE MODIFIERS###
###SON MISSION MODIFIERS###
###KON MISSION MODIFIERS###
###ZIM MISSION MODIFIERS###
###JEWS###
###KONGO###
###PRIMARY CULTS###
###JUNIOR CULTS###
###JUDAISM MODIFIERS###
###MECHANIC MODIFIERS###
###IDEAS###
###MODIFIERS###
###EVENTS###
#EAST AFRICAN MISSIONS
#EAST AFRICAN MODIFIERS
###CENTRAL AFRICAN GENERIC MISSIONS
###CENTRAL AFRICAN GENERIC MISSIONS MODIFIERS
###GENERIC HORN OF AFRICA MISSIONS###
###WEST AFRICA MISSIONS###
###MORE MISSIONS###
###EVENTS###
