###ETH FLAVOR EVENTS###
flavor_eth.29.t코0=[Root.GetName]의 이동하는 수도
###MAL FLAVOR EVENTS###
###SON FLAVOR EVENTS###
###COMET EVENTS###
###KONGO FLAVOR EVENTS###
###MUTAPA FLAVOR EVENTS###
###AJUURAN FLAVOR EVENTS###
###ADA FLAVOR EVENTS###
###HEIR CULT###
###COUNTRIES###
###CULTURES###
###MERCENARY COMPANIES###
###UNIT MODIFIER###
###GOVERNMENT REFORMS###
###ESTATE PRIVILEGES###
###TRADE MODIFIER###
###SCRIPTED EFFECTS AND TRIGGERS###
###DISASTER###
###BUILDINGS###
###IDEAS###
###DECISIONS###
###MAL DECISIONS###
###CUSTOM LOCALIZATION###
###JEWISH MECHANICS###
###OPINION###
###DECISIONS###
###ZIM MODIFIERS###
###ADAL MODIFIERS###
###CATHOLICISM###
###PP###
###MISSIONS###
###MAL MISSIONS###
###SON MISSIONS###
###KON MISSIONS###
###ZIM MISSIONS###
###AJU MISSIONS###
###ZAN MISSIONS###
###AJU MODIFIERS###
###ZAN MISSIONS###
###ETHIOPIA MISSION REWARDS###
###OPINION MODIFIERS###
###MALI MISSION MODIFIERS###
###MALI EVENT MODIFIERS###
###ESTATES###
###ESTATE MODIFIERS###
###SON MISSION MODIFIERS###
###KON MISSION MODIFIERS###
###ZIM MISSION MODIFIERS###
###JEWS###
###KONGO###
###PRIMARY CULTS###
###JUNIOR CULTS###
###JUDAISM MODIFIERS###
###MECHANIC MODIFIERS###
###IDEAS###
###MODIFIERS###
###EVENTS###
#EAST AFRICAN MISSIONS
#EAST AFRICAN MODIFIERS
###CENTRAL AFRICAN GENERIC MISSIONS
###CENTRAL AFRICAN GENERIC MISSIONS MODIFIERS
###GENERIC HORN OF AFRICA MISSIONS###
###WEST AFRICA MISSIONS###
###MORE MISSIONS###
###EVENTS###
