shiva코0=시바
ganesha코0=가네샤
surya코0=수리아
ganga코0=강가
shakti코0=샤크티
vishnu코0=비슈누
shiva_desc코0=시바는 파괴를 통한 변화의 신이며 춤의 주인이다.
ganesha_desc코0=가네샤는 지식과 시작의 신이며 장애들을 관장하는 신이다(장애들을 풀어주는 신).
surya_desc코0=수리야는 태양신이며 용기와 의지의 신이다.
ganga_desc코0=강가는 성스러운 강인 겐지스 강의 여신으로 정화하고 구원한다.
shakti_desc코0=샤크티는 힘과 역동적인 기운(정력)의 여신이다
vishnu_desc코0=비쉬누는 세계를 지탱하는 보편적인 신이다.
RV_NO_DEITY_TITLE코0=현재 믿는 신이 없음
RV_NO_DEITY_DESC코0=당신의 종교는 당신이 주신으로서 따르고 싶은 신을 선택할 수 있게 합니다. 각 신은 각자의 효과를 지니고 당신의 군주가 바뀔 때까지 유지됩니다.
RV_PICK_DEITY_THIS코0=$NAME|Y$ 신을 따름
RV_PICK_DEITY코0=신을 선택하기
norse_pagan_reformed코0=Norse
jewish_group코0=Jewish
jewish코0=Jewish
karaite코0=Karaite
samaritan코0=Samaritan
OLD_NORSE코0=Old Norse
catholic_neutral코0=트리엔트 공의회에서 중립 선택
catholic_concilatory코0=트리엔트 공의회에서 회유책 선택
catholic_harsh코0=트리엔트 공의회에서 강경책 선택
jewish_rebels_demand코0=$COUNTRYNAME$ 개종
jewish_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
jewish_rebels_title코0=종교적
jewish_rebels_name코0=$RELIGION$ 광신도
jewish_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
jewish_rebels_army코0=$RELIGION$군
norse_pagan_reformed_rebels_demand코0=$COUNTRYNAME$ 개종
norse_pagan_reformed_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
norse_pagan_reformed_rebels_title코0=종교적
norse_pagan_reformed_rebels_name코0=$RELIGION$ 광신도
norse_pagan_reformed_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
norse_pagan_reformed_rebels_army코0=$RELIGION$군
odin코0=오딘
odin_desc코0=오딘은 북구신화의 주신으로 주로 전쟁과 승리 그리고 죽음과 관련되어 있다.
freya코0=프레이야
freya_desc코0=프레이야는 사랑과 아름다움, 다산과 풍요를 약속하는 여신입니다.
tor코0=토르
tor_desc코0=토르는 오딘신의 아들이며 미드가르드(인간세계)에 들어가려는 두려운 존재들에 대항하여 인류를 지키는 신아다.
tyr코0=티르
tyr_desc코0=티르는 손이 하나인 정의의 신이며 가장 용감한 신들중 하나다.
snotra코0=스노트라
snotra_desc코0=스노트라는 지혜의 여신이다. 현명한 남자나 여자는 스노트라에 대한 존경심을 담아 스노트르라고 불렸다.
njord코0=뇨르드
njord_desc코0=프레이야의 아버지, 바다의 신, 그리고 그의 신자들의 식탁에 양식을 보장해준다
MESOAMERICAN_HERETIC코0=호랑이 입(Tenocelome)
NAHUATL_HERETIC코0=호랑이 입(Tenocelome)
INTI_HERETIC코0=후아카 신봉자들
MAZDAKI코0=Mazdaki
MANICHEAN코0=Manichean
OLD_TENGRI코0=Old Tengri
spreading_of_norse_rituals_title코0=북구 신화 의례의 전파
spreading_of_norse_rituals_desc코0=북구 신화로 전향하는 데에는 아무 것도 필요하지 않습니다. 모든 사람은 그들 고유의 종교적 의식을 행할 수 있습니다. 당신이 아사신족들-오딘, 토르, 프레이야, 스노트라-을 경외하는 만큼 당신은 아사트루(아사신족에 대한 믿음) 신봉자로서 여겨질 것입니다. 우리로 하여금 우리의 봉신들을 우리의 신들에 대해 배우도록 권장하게 하십시오. 그러면 그들은 최소한 우리의 신들을 예배하기 시작할 수 있습니다.
restrict_government_offices_title코0=유대교로 전향하도록 권장하다.
restrict_government_offices_desc코0=모든 중앙정부, 지방, 군사적 중요 시설들의 관리를 오직 참된 신앙을 믿는 자들에게만 맡기고, 탈무드와 유대 법전을 하급 관리들에게 무료로 교육합니다. 우리는 이러한 방법을 통해 개종을 향한 의지와 각오 모두를 다질 수 있습니다.
restricted_offices코0=전향을 권장하다.
desc_restricted_offices코0=불신자들에게는 권리를 제한하고 유대교 교육을 권장함으로써, 우리 국가에 속한 비 유대교인들이 참된 신앙으로 개종하도록 유도합니다.
spreading_norse_rituals코0=의식의 전파
desc_spreading_norse_rituals코0=우리는 북구신화를 믿지 않는 사람들에게 우리 종교의 신들과 의례를 배우도록 활동적으로 장려하고 있다.
inti_rebels_title코0=종교적
inti_rebels_name코0=$RELIGION$ 광신도
inti_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
inti_rebels_army코0=$RELIGION$군
inti_rebels_demand코0=$COUNTRYNAME$ 개종
inti_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
maya_rebels_title코0=종교적
maya_rebels_name코0=$RELIGION$ 광신도
maya_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
maya_rebels_army코0=$RELIGION$군
maya_rebels_demand코0=$COUNTRYNAME$ 개종
maya_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
nahuatl_rebels_title코0=종교적
nahuatl_rebels_name코0=$RELIGION$ 광신도
nahuatl_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
nahuatl_rebels_army코0=$RELIGION$군
nahuatl_rebels_demand코0=$COUNTRYNAME$ 개종
nahuatl_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
tengri_pagan_reformed코0=Tengri
tengri_pagan_reformed_rebels_demand코0=$COUNTRYNAME$ 개종
tengri_pagan_reformed_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
tengri_pagan_reformed_rebels_title코0=종교적
tengri_pagan_reformed_rebels_name코0=$RELIGION$ 광신도
tengri_pagan_reformed_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
tengri_pagan_reformed_rebels_army코0=$RELIGION$군
zoroastrian_group코0=Zoroastrian
zoroastrian코0=Zoroastrian
zoroastrian_rebels_demand코0=$COUNTRYNAME$ 개종
zoroastrian_rebels_demand_desc코0=종교 반군이 믿음을 위해 싸웁니다. 그들은 우리가 이 종교의 우월적 지위를 인정하거나, 적어도 그들을 개종시키려는 우리의 노력을 중지하고 평화롭게 숭배하도록 둘 것을 요구합니다.
zoroastrian_rebels_title코0=종교적
zoroastrian_rebels_name코0=$RELIGION$ 광신도
zoroastrian_rebels_desc코0=종교적 광신도들은 자신들과 다른 신앙의 국가가 지배하는 지역에서 궐기하는 경향이 있습니다. 그들은 자신들의 믿음을 퍼뜨리고 이단들을 모두 처단하려 할 것입니다.
zoroastrian_rebels_army코0=$RELIGION$군
jewish_flavor.1.t코0=유월절(Pesach)
jewish_flavor.1.d코0=모세가 파라오로 부터 우리 백성들을 해방한지도 오래전 일입니다만, 과거에 주님께서 파라오를 어떻게 처벌하셨는지에 대해 기억해야 합니다. 그분의 명에 따라 문의 인방과 설주에 어린 양의 피로 표시를 해두었고, 죽음의 천사들이 우리의 첫번째 자녀들을 죽이지 못하게 막았습니다. 그 후로 우리는 파라오의 족쇄에서 벗어났지만, 여전히 우리는 이를 마음속 깊이 새기며 기려야 합니다. \n 성경의 중요한 세 절기중 하나로써 유월절을 기념하며, 그것을 항시 염두해 두어야 합니다. 예루살렘 순례에서 희생양을 제공하는게 관례였지만, 이는 제 2 성전이 파괴된 이후로 불가능해졌습니다. 고로, 추가적인 수고를 댓가로 이를 기념하고 기억할 것입니다. 희생에 쓰일 새끼양이 주어질것이고, 이스트를 쓴 빵들은 버리거나 태웁니다. 이렇게, 우린 기억할 것입니다.
jewish_flavor.1.a코0=즐기도록 하지
jewish_flavor.2.t코0=칠칠절(shavuot)
jewish_flavor.2.d코0=파라오의 땅을 떠나, 우리 민족은 40년간 사막을 떠돌아 다니다 약속에 땅에 도착했습니다. 그 시기에, 시나이 산에서 모세가 주님께 토라(Torah)를 받았습니다. 이를 기념하는 것이 칠칠절이고, 샬로쉬 레갈림(Shalosh Regalim)이라 하는 세 명절 중 하나입니다. 관습적으로 샬로쉬 레길림이 되면 예루살렘으로 향하는 순례길에 올라 희생양을 제공하는 것이 한 부분이 었지만, 제 2성전이 파괴된 이후 이는 불가능한 사항이 되었습니다. 그러므로, 추가적인 수고를 댓가로 이를 기념하고 기억할 것입니다.\n칠칠절엔 유월절 부터 시작된 오메르라는 밀 추수기간의 마지막을 기억하는데 쓰이기도 합니다. 그러므로, 칠칠절은 토라를 받는 기대와 욕망을 대표하며 반드시 이를 명심하고 기념해야 합니다. 우린 토라 공부 집중하여 주님을 섬기는데 충실한 국가가 되는 것에 중점을 두어야 합니다. 그제서야 주님께서 준비된 것을 주실 것입니다.
jewish_flavor.2.a코0=다 같이 기념하세.
jewish_flavor.3.t코0=초막절(Sukkot)
jewish_flavor.3.d코0=파라오의 땅을 떠나, 우리 민족은 40년간 사막을 떠돌아 다니다 약속에 땅에 도착했습니다. 그 모든 기간 동안, 우리 백성들은 사막 한복판에 세워진 부실한 곳에 살았습니다.\n 이를 기념하는것이 초막절이고, 샬로쉬 레갈림(Shalosh Regalim)이라 하는 세 명절 중 하나입니다. 관습적으로 샬로쉬 레길림이 되면 예루살렘으로 향하는 순례길에 올라 희생양을 제공하는 것이 한 부분이 었지만, 제 2성전이 파괴된 이후 이는 불가능한 사항이 되었습니다. 그러므로, 추가적인 수고를 댓가로 이를 기념하고 기억할 것입니다.\n 우리는 초막절 기간동안 한시적인 거주지를 짓고 거기서 생활하는 것으로 우리 민족이 과거에 고통받은 일을 나누고 기억할 것입니다. 그리고 고통을 나누는 것에 참여하는 전부가 우리 스스로를 갈라놓는 것보다 많은 공통점이 있다는 것을 각인시켜 줄 것입니다. 
jewish_flavor.3.a코0=기념하세.
jewish_flavor.4.t코0=유대식 성인식(Bar Mitzvah)
jewish_flavor.4.desc코0=[Root.Monarch.GetTitle] 후계자 [Root.Heir.GetName]가 태어난 것이 마치 어제 같습니다만, 벌써 [Root.Heir.GetHerHim]가 완연히 성인이 될 때가 되었습니다. 유대법에 따라 [Root.Monarch.GetTitle] [Root.Monarch.GetName]께서 [Root.Heir.GetSheHe]의 책임을 지어야 했지만, 이제부터 [Root.Heir.GetSheHe]은 자신인 [Root.Heir.GetHerHis] 행동에 책임을 지어야 할것입니다.\n 유대인 사이에서 전통적으로 언제나처럼 남자는 13세 여자는 12세에, 그들은 집단의 다 성장한 구성원이 되고 여기엔 책임이 따릅니다. 이미 유대 성경 토라를 읽을 수있고, 최소한 10명의 인원이 중심이 되는 기도 모임을 이끌거나 거기에 참여할 수 있으며, 결혼할 권리도 얻었습니다. 그러다 유대법을 알고 그것을 준수할 의무 또한 갖게 됩니다.\n이 모든 일들을 기념하기 위해 우리가 바르 미츠바를 주최할 것이라 생각들 하고 있습니다. 또한 [Root.Heir.GetName]을 궁중에 소개하거나, [Root.Heir.GetHerHim]가 [Root.Heir.GetHerHis] 궁정과의 유대를 강화하기에 좋은 기회가 되어.  [Root.Heir.GetSheHe]가 우리나라를 다스리기 시작한다면 [Root.Heir.GetHerHim]를 준비된 인물로 만들것입니다.
jewish_flavor.4.a코0=아낌없이 써보는 거야.
jewish_flavor.4.b코0=그냥 선만 넘지 말자고.
jewish_flavor.4.c코0=겸손할 필요가 있다.
jewish_flavor.4.d코0=기념할 필요가 없다.
lavish_bmv코0=호화로운 바르 미츠바
desc_lavish_bmv코0=[Root.Heir.GetName]는 호화로운 바르 미츠바 축제를 보냈습니다.
normal_bmv코0=일반적인 바르 미츠바
desc_normal_bmv코0=[Root.Heir.GetName]는 일반 바르 미츠바 축제를 보냈습니다.
cheap_bmv코0=겸손한 방식의 바르 미츠바
desc_cheap_bmv코0=[Root.Heir.GetName]는 전혀 호화롭지않은 바르 미츠바 축제를 보냈습니다.
no_bmv코0=바르 미츠바하지 않기
desc_no_bmv코0=[Root.Heir.GetName]를 위한 바르 미츠바를 열지 않았습니다.
shalosh_regalim_modifier코0=샬로쉬 레갈림(유대인의 세가지 명절)
desc_shalosh_regalim_modifier코0=샬로쉬 레갈림은 가장 성스로운 기념일들로, 필요한 모든 것을 신중히 준비해야 합니다.
passover_modifier코0=유월절(Pesach)
desc_passover_modifier코0=성공적인 유월절이 지나고, 주님게서 그들을 지킬 거라고 믿는 우리 백성들은 쉴 수 있게 됐습니다.
passover_tooltip코0=§Y가축§!을 생산하는 모든 지역은 §Y샬로쉬 레길림§! 모디파이어를 받습니다! §Y1 년§!동안, 다음효과를 받습니다:\n 지역 생산 효율성 §G+10%§!
shavuot_modifier코0=칠칠절(shavuot)
desc_shavuot_modifier코0=우리가 많은 곡물이란 축복을 받진 못했더라도, 우리 이웃들과의 성공적인 외교 관계는 문제없이 칠칠절을 기념할 수 있게 했습니다.
shavuot_tooltip코0=모든 §Y곡물§! 생산 지역은 §Y샬로쉬 레갈림§ 모디파이어를 받습니다! §Y1 년§! 동안, 다음 효과를 줍니다:\n지역 생산 효율성: §G+10%§!.
sukkot_modifier코0=초막절(Sukkot)
desc_sukkot_modifier코0=우리가 초막절을 기념하며 여려움을 나누는 일은 우리 백성사이에서 공유하는 정체성을 인식시키게 합니다.
jewish_flavor.5.t코0=제 3성전
jewish_flavor.5.d코0=예루살렘이 다시 한번 우리의 것이 되었고, 다수의 인구가 주님을 섬기게 되었습니다. 제 2성전이 예루살렘의 로마군 포위기간동안 파괴된 이래, 수백만의 유대인이 꿈궈 오던 그 꿈을 실천에 옮기기에 좋은 기회입니다. 새 성전은 예의 성전보다도 더 대단할 것입니다.\n그러나 문제가 존재하니, 새 성전이 들어설 '성전산'이 알 아크사 지구가 되었기에 무슬림에게도 성지이기 때문입니다. 새 성전을 원래 장소에 지어야 할까요? 그렇다면 알 아크사 지구를 철거할 필요가 있고 무슬림을 분노케할 터 입니다. 그냥 재료만 재취합할 수도 있습니다. 우리 계획을 더 싸게 치룰 수 있겠습니다. 반면, 아예 새로운 장소에 지어야 할까요? 성지가 아닌 곳을 골라 새 천년의 믿음을 저버리는 것이기 때문에 랍비들은 정말로 언짢아 할 것입니다.\n어찌해야 좋을까요?
jewish_flavor.5.a코0=무슬림이 주님을 권능을 넘지 않을지니. 우리는 그 분의 성전이 속한 곳에 세우리라.
jewish_flavor.5.b코0=아마 중간 쯤이 나을지도 모르겠군. 세계의 절반을 적으로 돌릴 필요는 없다.
jewish_flavor.5.c코0=최선의 순간은 아닐지도 모르겠군, 아무튼 말이지.
third_temple_provincial_modifier코0=제 3성전
desc_third_temple_provincial_modifier코0=역사적으로 세번째로 성전은 성스로운 도시 예루살렘의 성전산을 차지했습니다.
third_temple_country_modifier코0=제 3성전이 지어졌습니다.
desc_third_temple_country_modifier코0=예루살렘의 제 3성전에서 하루 세차례 예배가 이제  현실이 되었습니다. 전 세계의 유대인들이 기뻐합니다.
third_temple_consequences_tooltip코0=§Y모든 무슬림 국가§!'의 우리에 대한 의견이 §R-200§! 만큼 변화되고, by 각 §Y2§!년 마다 개선됩니다.\n§Y모든 무슬림 국가§!가 §Y외교적 모욕§!을 얻게됩니다. 우리에 대한 전쟁 목표가 §Y5 years§!간 지속됩니다.\n§Y무슬림§! 지방에서 반란이 생깁니다.
destroyed_al_aqsa_opinion코0=알 아크사 지구를 파괴했다.
build_the_third_temple_title코0=제 3성전을 짓다.
build_the_third_temple_desc코0=수세기 동안, 제 2성전의 소실을 슬퍼했고, 재복원의 꿈을 꾸었습니다. 때가 왔습니다. 예루살렘에 주의 영광을 위해 바칠 제 3성전을 지어야합니다.
jewish_flavor.6.t코0=다시 주님의 품으로
jewish_flavor.6.d코0=유대교는 전도를 하지않는 종교이기에 우리 소규모 집단에 새로운 피를 수혈하기엔 더 까다롭습니다. 여기에 더해, 우리 전통에 따르면, 오직 유대인 여성의 몸에서 난 아이만이 유대인이 될 것이고, 따라서 우리의 믿음을 따르는 여성이 신부인 종류의 종교간 결혼을 허용하기에는 위험이 따르게 됩니다.\n고맙게도, [Root.GetName]의 이전에 다른 아브라함계 종교를 따르던 백성들은 줄곧 주님을 믿어왔음을 깨달았고, 그들의 유대인 정체성을 온전히 받아드렸습니다.
jewish_flavor.6.a코0=그들의 믿음이 진실되다면 언제나 환영받으리니.
jewish_flavor.7.t코0=안식일의 중요 문제
jewish_flavor.7.d코0=오늘은 안식일이기에 모든 유대인들은 휴식하고 그들의 예배에 시간을 바쳐야 합니다. 그러나, 엄청난 중요한 문제거리가 일어나 일부 조언자들은 [Root.Monarch.GetName]께서 주목하길 바랍니다. 단지 이 한 제안에 랍비들의 눈썹은 치켜올려지고, 빠르게 경멸의 말이 궁정을 메웁니다. 무슨 선택을 해도 누군가는 화가 날 것으로 보이는군요. 하지만 과연 차악은 어떤 것일까요?
jewish_flavor.7.a코0=안식일은 지켜야지. 문제가 무엇이건, 보류될 수 있다.
jewish_flavor.7.b코0=국가 운영는 항상 주도적이어한다. 가능한 빨리 문제 해결을 하고 예배로 돌아가자.
jewish_flavor.7.c코0=독실한 한 사람의 신자로서, [Root.Monarch.GetName]은 기도 외엔 하지 않을 것이다. 이의제기는 묵살될것이다.
jewish_flavor.7.e코0=통치문제 중요성은 종교를 상회한다. [Root.Monarch.GetName]가 시간이 있을 때까지 미뤄질 수 있다. 
jewish_flavor.8.t코0=메시아
jewish_flavor.8.d코0=우리 백성들은 디아스포라 이후 줄곧 성지로 돌아가기를 갈망했습니다. 비록 아직 여전히 전 세계에 흩어져 있지만, [Root.Monarch.GetName] 이 혹여 오래 고대하던 메시아 일지도 모른다고 작게 속삭이는 자 들이 생겼습니다. 신께서 우리를 성지로 돌려보내주실까요, 아니라면 이 문제를 우리 손으로 직접 해결해야만 할까요?
jewish_flavor.8.a코0=주님께서 유대민족을 돌보시리라. [Root.Monarch.GetName] 은 메시아가 아니다.
jewish_flavor.8.b코0=메시아인 [Root.Monarch.GetName] 께서 시온의 땅으로 보내 주실것이다.
no_messiah_country_modifier코0=통치자는 메시아가 아니다
desc_no_messiah_country_modifier코0=통치자 [Root.Monarch.GetName] 는 우린 성지로 데려가줄 메시아가 아니지만, 신께서 마땅히 그렇게 하시리.
estate_not_built_temple코0=미래의 사원 재건 약속

